import type { StatusEntry } from './types.js';

export const STATUS_REGISTRY = {
	'etl.intake.job_complete': {
		code: 'etl.intake.job_complete',
		type: 'https://guide.steamco.studio/status/etl.intake.job_complete',
		category: 'success',
		title: 'ETL job finished for {project}.',
		detail: '{rows, plural, one {# row} other {# rows}} processed.',
		remediation: 'Review the output in the job monitor.',
		owning_feature: 'etl.intake',
		surfaces: ['notification-center', 'toast', 'log'],
		doc_url: '/docs/etl/intake#job-complete',
		telemetry_event: 'etl_intake_job_complete',
		provenance: true,
		since: 'v0.4',
	},
	'library.ingest.duplicate_smiles': {
		code: 'library.ingest.duplicate_smiles',
		type: 'https://guide.steamco.studio/status/library.ingest.duplicate_smiles',
		category: 'error',
		http_status: 409,
		title: '{n, plural, one {# compound} other {# compounds}} already in {library}.',
		detail: 'Deduplicated on canonical SMILES.',
		remediation: 'Review duplicates or force-add.',
		owning_feature: 'library.ingest',
		surfaces: ['toast', 'notification-center', 'inline', 'log', 'api'],
		doc_url: '/docs/library/ingest#duplicates',
		telemetry_event: 'library_ingest_duplicate',
		provenance: true,
		since: 'v0.4',
	},
	'reactivity.premise_changed': {
		code: 'reactivity.premise_changed',
		type: 'https://guide.steamco.studio/status/reactivity.premise_changed',
		category: 'warning',
		title: 'Premise changed in {project} — review {cell}.',
		detail: 'A linked premise was updated; downstream values may be stale.',
		remediation: 'Open the cell and confirm whether to accept the new premise.',
		owning_feature: 'reactivity',
		surfaces: ['notification-center', 'inline', 'log'],
		doc_url: '/docs/reactivity/premise-changed',
		telemetry_event: 'reactivity_premise_changed',
		provenance: true,
		since: 'v0.4',
	},
	'notification.center.mark_all_read': {
		code: 'notification.center.mark_all_read',
		type: 'https://guide.steamco.studio/status/notification.center.mark_all_read',
		category: 'success',
		title: 'Marked {count, plural, one {# notification} other {# notifications}} as read.',
		detail: 'Inbox triage updated.',
		owning_feature: 'notification.center',
		surfaces: ['toast', 'notification-center', 'log'],
		doc_url: '/docs/notifications/center#mark-all-read',
		telemetry_event: 'notification_center_mark_all_read',
		since: 'v0.4',
	},
	'etl.intake.automap_failed': {
		code: 'etl.intake.automap_failed',
		type: 'https://guide.steamco.studio/status/etl.intake.automap_failed',
		category: 'error',
		http_status: 422,
		title: 'Automap failed for {project}.',
		detail: '{issues, plural, one {# column} other {# columns}} could not be mapped.',
		remediation: 'Open the intake wizard and map columns manually.',
		owning_feature: 'etl.intake',
		surfaces: ['notification-center', 'inline', 'log', 'api'],
		doc_url: '/docs/etl/intake#automap-failed',
		telemetry_event: 'etl_intake_automap_failed',
		provenance: true,
		since: 'v0.4',
	},
} as const satisfies Record<string, StatusEntry>;

export type StatusCode = keyof typeof STATUS_REGISTRY;
